version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-test
    ports:
      - "8080:80"
    networks:
      - kafka-net

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  broker:
    image: wurstmeister/kafka:latest
    container_name: kafka-broker
    ports:
      - "9092:9092"  # Broker port for internal communication
      - "29092:29092"  # Broker port for external communication
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  cettire-sitemaps-scraper:
    build:
      context: ./cettire-sitemaps-scraper
      dockerfile: Dockerfile
    volumes:
      - ./cettire-sitemaps-scraper:/usr/src/app
    environment:
      KAFKA_BROKER: kafka-broker:9092
    depends_on:
      - broker
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
