version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  service-a:
    build:
      context: ./services/service-a
      dockerfile: Dockerfile
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
        
  cettire-sitemaps-scraper:
    build:
      context: ./services/cettire-sitemaps-scraper
      dockerfile: Dockerfile
    volumes:
      - cettire-sitemaps-scraper:/usr/src/app
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

volumes:
  service-a-data:
  cettire-sitemaps-scraper: